spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/forum?serverTimezone=Asia/Shanghai'
    username: 'root'
    password: 'wegfan'
  redis:
    host: 'localhost'
    port: 6379
    database: 0
    password: ''
    