spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: 'jdbc:p6spy:mysql://localhost:3306/forum?serverTimezone=Asia/Shanghai'
    username: 'root'
    password: 'wegfan'
  redis:
    host: 'localhost'
    port: 6379
    database: 0
    password: ''
    